# Generated by Django 3.2.7 on 2021-09-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbsize',
            name='height',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='thumbsize',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='thumbsize',
            name='width',
        ),
    ]
