# Generated by Django 3.2.7 on 2021-09-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('picstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpladedImage',
            new_name='UploadedImage',
        ),
    ]
