# Generated by Django 3.2.7 on 2021-09-11 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('picstore', '0002_rename_upladedimage_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='filename',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='picstore.imageset'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.thumbsize'),
        ),
        migrations.CreateModel(
            name='TimedImageLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expire_by_date', models.DateTimeField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picstore.uploadedimage')),
            ],
        ),
    ]
