# Generated by Django 3.2.7 on 2021-09-11 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picstore', '0003_auto_20210911_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageset',
            name='filename',
        ),
    ]
