# Generated by Django 3.2.7 on 2021-09-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picstore', '0004_remove_imageset_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageset',
            options={'ordering': ['id'], 'verbose_name_plural': 'Image Sets'},
        ),
        migrations.AlterModelOptions(
            name='timedimagelink',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Time Restricted Links'},
        ),
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['id'], 'verbose_name_plural': 'User Images'},
        ),
    ]
