# Generated by Django 3.2.7 on 2022-07-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picstore', '0005_auto_20210912_1005'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timedimagelink',
            index=models.Index(fields=['-id'], name='picstore_ti_id_26e94b_idx'),
        ),
    ]
